title: Cloud Threat Hunter: Real-Time Detection of Brute Force and Malware Attacks 
description: Deploying ELK in the Cloud to Combat Evolving Threats with Automated Incident Response
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
